# Generated by Django 4.0.4 on 2022-05-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_signal_asset_delete_asset_delete_signal"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
