# Generated by Django 4.0.4 on 2022-05-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_signal_signal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['date', 'asset']},
        ),
        migrations.AddField(
            model_name='asset',
            name='long_description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='short_description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['name'], name='api_asset_name_3e5e22_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['date', 'asset'], name='api_signal_date_65385c_idx'),
        ),
        migrations.AddIndex(
            model_name='signal',
            index=models.Index(fields=['asset', 'signal'], name='api_signal_asset_i_f4abe7_idx'),
        ),
    ]
