# Generated by Django 4.0.4 on 2022-04-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_signal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='name',
            new_name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='ticker',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
