# Generated by Django 4.0.4 on 2022-04-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_name_signal_asset_asset_ticker_signal_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='type',
            new_name='signal',
        ),
        migrations.AddField(
            model_name='signal',
            name='closing_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='opening_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
