# Generated by Django 4.0.4 on 2022-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_rename_type_signal_signal_signal_closing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='note',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='performance_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='performance_usd',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='shade',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
